
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ll='ls -l --group-directories-first --color=auto'
alias la='ls -a --group-directories-first --color=auto'

PS1='\[\e[1;38;5;196m\][\u@\h \W]#\[\e[0m\] '
