---
# File tasks for the development role
- name: copy sourcing bash_profile
  copy:
    src: home/user/bash_profile
    dest: /home/mpatton/.bash_profile
    owner: mpatton
    group: users

- name: copy sourcing bashrc
  copy: 
    src: home/user/bashrc
    dest: /home/mpatton/.bashrc
    owner: mpatton
    group: users

- name: copy actual user config files
  copy: 
    src: home/user/config/
    dest: /home/mpatton/.config/
    owner: mpatton
    group: users

- name: copy Pictures directory
  copy:
    src: home/user/Pictures/
    dest: /home/mpatton/Pictures/
    owner: mpatton
    group: users

- name: add symlink for wallpaper
  file:
      src: /home/mpatton/Pictures/wallpaper/digital-rain.png
      dest: /home/mpatton/.wallpaper
      owner: mpatton
      group: users
      state: link
...
