---
# File tasks for the development role
- name: copy sourcing bash_profile
  copy:
    src: home/user/bash_profile
    dest: /home/mpatton/.bash_profile
    owner: mpatton
    group: users

- name: copy sourcing bashrc
  copy: 
    src: home/user/bashrc
    dest: /home/mpatton/.bashrc
    owner: mpatton
    group: users

- name: copy actual user config files
  copy: 
    src: home/user/config/
    dest: /home/mpatton/.config/
    owner: mpatton
    group: users

- name: copy Pictures directory
  copy:
    src: home/user/Pictures/
    dest: /home/mpatton/Pictures/
    owner: mpatton
    group: users

- name: add symlink for wallpaper
  file:
    src: home/user/Pictures/wallpapers/digital-rain.png
    dest: /home/mpatton/.wallpaper
    owner: mpatton
    group: users
    state: link

- name: copy display manager config
  file:
    src: etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root

- name: copy greeter config
  file:
    src: etc/lightdm/lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    owner: root
    group: root

- name: copy backgrounds for greeter
  file:
    src: etc/lightdm/backgrounds/
    dest: /etc/lightdm/backgrounds/
    owner: root
    group: root
...
