---
# File tasks for the common role
- name: copy nvPY config file
  copy:
    src: home/user/nvpy.cfg
    dest: /home/mpatton/.nvpy.cfg
    owner: mpatton
    group: users

- name: copy config directory
  copy:
    src: home/user/config/
    dest: /home/mpatton/.config/
    owner: mpatton
    group: users

- name: add symlink for vim directory
  file: 
    src: home/mpatton/.config/vim/
    dest: /home/mpatton/.vim
    owner: mpatton
    group: users
    state: link

- name: copy sudoers file
  copy:
    src: etc/sudoers
    dest: /etc/sudoers
    owner: root
    group: root

- name: copy bashrc for root
  copy:
    src: root/bashrc
    dest: /root/.bashrc
    owner: root
    group: root

- name: copy file of post-install tasks
  copy:
    src: home/user/README.md
    dest: /home/mpatton/README.md
    owner: mpatton
    group: users

- name: create directory for vim plugins
  file:
    path: /home/mpatton/.config/vim/bundle
    owner: mpatton
    group: users
    state: directory

- name: install vim plugins
  git: repo=https://github.com/{{ item.gitroot }}/{{ item.gitname }}.git
       dest=/home/mpatton/.config/vim/bundle/{{ item.gitname }}
  with_items: "{{ vim_plugin_list }}"
...
