---
# File tasks for the common role
- name: copy sourcing vimrc
  copy: 
    src: home/user/vimrc 
    dest: /home/mpatton/.vimrc
    owner: mpatton
    group: users

- name: copy config directory
  copy:
    src: home/user/config/
    dest: /home/mpatton/.config
    owner: mpatton
    group: users

- name: copy vim directory
  copy:
    src: home/user/vim/
    dest: /home/mpatton/.vim
    owner: mpatton
    group: users

- name: copy sudoers file
  copy:
    src: etc/sudoers
    dest: /etc/sudoers
    owner: root
    group: root

- name: copy root's bashrc
  copy:
    src: root/bashrc
    dest: /root/.bashrc
    owner: root
    group: root
...
