---
# File tasks for the common role
- name: copy sourcing vimrc
  copy: 
    src: home/user/vimrc 
    dest: /home/mpatton/.vimrc
    owner: mpatton
    group: users

- name: copy actual vimrc
  copy:
    src: home/user/config/vim/vimrc-real
    dest: /home/mpatton/.config/vim/vimrc-real
    owner: mpatton
    group: users

- name: copy vim directory
  copy:
    src: home/user/vim
    dest: /home/mpatton/.vim
    owner: mpatton
    group: users

- name: copy git directory
  copy:
    src: home/user/config/git
    dest: /home/mpatton/.config/git
    owner: mpatton
    group: users
...
